DO NOT MERGE Arm teleop added
fetchrobotics/fetch_ros pull request #54
Opened 2016-09-15 19:37 UTC by HanjunSong-Fetch

2016-09-20 20:42 UTC, mikeferguson commented on fetch_teleop/src/joystick_teleop.cpp
> +    }
revert - non-style change

2016-09-20 20:51 UTC, mikeferguson commented on fetch_teleop/src/joystick_teleop.cpp
> +    pnh.param("button_deadman", deadman_end_, 11);
same parameter name as previous parameter, should have a different name (perhaps "button_deadman_arm")

2016-09-20 20:52 UTC, mikeferguson commented on fetch_teleop/src/joystick_teleop.cpp
> +      //geometry_msgs::Twist goal;
remove this line

2016-09-20 20:53 UTC, mikeferguson commented on fetch_teleop/src/joystick_teleop.cpp
> +  int deadman_body_, deadman_end_, open_button_, close_button_;
i presume "end" means "end effector", but it would probably be better to call this "deadman_arm_" since we call it "ArmTeleop" below

2016-09-20 20:54 UTC, mikeferguson commented on fetch_teleop/src/joystick_teleop.cpp
> +    pnh.param("button_end_frame", button_end_frame_, 11);
spell it out -- "end_effector" -- for clarity

2016-09-20 20:55 UTC, mikeferguson commented on fetch_teleop/src/joystick_teleop.cpp
> +    if(button_body_frame_pressed)
space after if (see additional instance below)

2016-09-20 20:56 UTC, mikeferguson commented on fetch_teleop/src/joystick_teleop.cpp
> +    components_.push_back(c);
these lines should be in the "if (is_fetch)" above -- we don't want arm teleop on freights

2016-09-20 20:56 UTC, mikeferguson requested changes

2016-09-23 23:18 UTC, mikeferguson commented on fetch_teleop/src/joystick_teleop.cpp
> +    pnh.param("button_deadman", deadman_body_, 9);
we should not be changing the default button here

2016-09-23 23:23 UTC, mikeferguson commented on fetch_teleop/src/joystick_teleop.cpp
> +    pnh.param("button_end_effector_frame", button_end_effector_frame_, 11);
how can this be the same as the deadman button?

2016-09-23 23:23 UTC, mikeferguson commented on fetch_teleop/src/joystick_teleop.cpp
> +    pnh.param("max_vel_roll", max_vel_roll_, -2.0);
why is this negative?

2016-09-23 23:28 UTC, mikeferguson commented on fetch_teleop/src/joystick_teleop.cpp
> +  boost::mutex odom_mutex_;
this is not used?

2016-09-23 23:29 UTC, mikeferguson commented on fetch_teleop/src/joystick_teleop.cpp
> +  ros::Publisher cmd_vel_pub_;
this should really just be called command_pub_ or cmd_pub_ -- cmd_vel really is synonymous with "base control" in ROS

2016-09-23 23:29 UTC, HanjunSong-Fetch commented on fetch_teleop/src/joystick_teleop.cpp
> +    pnh.param("button_end_effector_frame", button_end_effector_frame_, 11);
This is not the same ones. I assigned different buttons for frame selection. Am I not supposed to assign more buttons?

2016-09-23 23:33 UTC, HanjunSong-Fetch commented on fetch_teleop/src/joystick_teleop.cpp
> +    pnh.param("max_vel_roll", max_vel_roll_, -2.0);
To synchronize with tilting motion. Maybe I should put '-' sign at the equation below?

2016-09-23 23:34 UTC, HanjunSong-Fetch commented on fetch_teleop/src/joystick_teleop.cpp
> +    pnh.param("button_deadman", deadman_body_, 9);
Got it I will restore that. Is it okay to add other deadman buttons such as deadman_body_, deadman_arm_ ? I added those for convenience.

2016-09-23 23:37 UTC, mikeferguson commented on fetch_teleop/src/joystick_teleop.cpp
> +    pnh.param("button_deadman", deadman_body_, 9);
It is fine to add additional deadman buttons (for instance, I think you want 3 deadmen, one for the body, one for ee frame, one for body frame -- basically saying regardless of what you are controlling, it's OK to enable the gripper buttons)

2016-09-23 23:41 UTC, HanjunSong-Fetch commented on fetch_teleop/src/joystick_teleop.cpp
> +  ros::Publisher cmd_vel_pub_;
changed

2016-09-23 23:41 UTC, HanjunSong-Fetch commented on fetch_teleop/src/joystick_teleop.cpp
> +  boost::mutex odom_mutex_;
it is not used. removed. max_windup_time also removed.

2017-06-12 00:21 UTC, mikeferguson commented
replaced by #61

2017-06-12 00:21 UTC, closed without merging