[fetch_depth_layer] Melodic: Update depth_layer no match for ‘operator=’ error
fetchrobotics/fetch_ros pull request #82
Opened 2018-07-22 21:51 UTC by josiahls

I recently checked out this branch and attempted to run catkin_make. There was an issue with how the cv::Ptr was being set. 

This is fixed by setting the normals_estimator_ pointer similarly to how the plane_estimator_ pointer is being set. The package can now compile. I am confused why I needed to change this, but I am curious to learn why. Obviously test this to make sure it actually runs, which I what I will be doing very soon.

Note, as of 7/22/2018 I have been referencing #81 to get this to work, and modified the files specified in that issue along with my one commit.

The error below would occur:
[ 97%] Building CXX object navigation/move_base/CMakeFiles/move_base.dir/src/move_base.cpp.o
/home/josiah/PycharmProjects/fetch_robot_ws/src/fetch_ros/fetch_depth_layer/src/depth_layer.cpp: In member function ‘void costmap_2d::FetchDepthLayer::depthImageCallback(const ConstPtr&)’:
/home/josiah/PycharmProjects/fetch_robot_ws/src/fetch_ros/fetch_depth_layer/src/depth_layer.cpp:239:28: error: no match for ‘operator=’ (operand types are ‘cv::Ptr<cv::rgbd::RgbdNormals>’ and ‘cv::rgbd::RgbdNormals*’)
       normals_estimator_ = new RgbdNormals(cv_ptr->image.rows,cv_ptr->image.cols,  cv_ptr->image.depth(),K_);
                            ^~~~
In file included from /usr/local/include/opencv2/core/cvstd.hpp:1033:0,
                 from /usr/local/include/opencv2/core/base.hpp:58,
                 from /usr/local/include/opencv2/core.hpp:54,
                 from /usr/local/include/opencv2/core/core.hpp:48,
                 from /opt/ros/melodic/include/cv_bridge/cv_bridge.h:43,
                 from /home/josiah/PycharmProjects/fetch_robot_ws/src/fetch_ros/fetch_depth_layer/include/fetch_depth_layer/depth_layer.h:37,
                 from /home/josiah/PycharmProjects/fetch_robot_ws/src/fetch_ros/fetch_depth_layer/src/depth_layer.cpp:32:
/usr/local/include/opencv2/core/ptr.inl.hpp:160:9: note: candidate: cv::Ptr<T>& cv::Ptr<T>::operator=(const cv::Ptr<T>&) [with T = cv::rgbd::RgbdNormals]
 Ptr<T>& Ptr<T>::operator = (const Ptr<T>& o)
         ^~~~~~
/usr/local/include/opencv2/core/ptr.inl.hpp:160:9: note:   no known conversion for argument 1 from ‘cv::rgbd::RgbdNormals*’ to ‘const cv::Ptr<cv::rgbd::RgbdNormals>&’
In file included from /usr/local/include/opencv2/core/base.hpp:58:0,
                 from /usr/local/include/opencv2/core.hpp:54,
                 from /usr/local/include/opencv2/core/core.hpp:48,
                 from /opt/ros/melodic/include/cv_bridge/cv_bridge.h:43,
                 from /home/josiah/PycharmProjects/fetch_robot_ws/src/fetch_ros/fetch_depth_layer/include/fetch_depth_layer/depth_layer.h:37,
                 from /home/josiah/PycharmProjects/fetch_robot_ws/src/fetch_ros/fetch_depth_layer/src/depth_layer.cpp:32:
/usr/local/include/opencv2/core/cvstd.hpp:333:10: note: candidate: template<class Y> cv::Ptr<T>& cv::Ptr<T>::operator=(const cv::Ptr<Y>&) [with Y = Y; T = cv::rgbd::RgbdNormals]
     Ptr& operator = (const Ptr<Y>& o);
          ^~~~~~~~
/usr/local/include/opencv2/core/cvstd.hpp:333:10: note:   template argument deduction/substitution failed:
/home/josiah/PycharmProjects/fetch_robot_ws/src/fetch_ros/fetch_depth_layer/src/depth_layer.cpp:239:28: note:   mismatched types ‘const cv::Ptr<T>’ and ‘cv::rgbd::RgbdNormals*’
       normals_estimator_ = temp;
                            ^~~~
In file included from /usr/local/include/opencv2/core/cvstd.hpp:1033:0,
                 from /usr/local/include/opencv2/core/base.hpp:58,
                 from /usr/local/include/opencv2/core.hpp:54,
                 from /usr/local/include/opencv2/core/core.hpp:48,
                 from /opt/ros/melodic/include/cv_bridge/cv_bridge.h:43,
                 from /home/josiah/PycharmProjects/fetch_robot_ws/src/fetch_ros/fetch_depth_layer/include/fetch_depth_layer/depth_layer.h:37,
                 from /home/josiah/PycharmProjects/fetch_robot_ws/src/fetch_ros/fetch_depth_layer/src/depth_layer.cpp:32:
/usr/local/include/opencv2/core/ptr.inl.hpp:263:9: note: candidate: cv::Ptr<T>& cv::Ptr<T>::operator=(cv::Ptr<T>&&) [with T = cv::rgbd::RgbdNormals]
 Ptr<T>& Ptr<T>::operator = (Ptr<T>&& o)
         ^~~~~~
/usr/local/include/opencv2/core/ptr.inl.hpp:263:9: note:   no known conversion for argument 1 from ‘cv::rgbd::RgbdNormals*’ to ‘cv::Ptr<cv::rgbd::RgbdNormals>&&’
fetch_ros/fetch_depth_layer/CMakeFiles/fetch_depth_layer.dir/build.make:62: recipe for target 'fetch_ros/fetch_depth_layer/CMakeFiles/fetch_depth_layer.dir/src/depth_layer.cpp.o' failed
make[2]: *** [fetch_ros/fetch_depth_layer/CMakeFiles/fetch_depth_layer.dir/src/depth_layer.cpp.o] Error 1
CMakeFiles/Makefile2:10133: recipe for target 'fetch_ros/fetch_depth_layer/CMakeFiles/fetch_depth_layer.dir/all' failed
make[1]: *** [fetch_ros/fetch_depth_layer/CMakeFiles/fetch_depth_layer.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 98%] Linking CXX shared library /home/josiah/PycharmProjects/fetch_robot_ws/devel/lib/libmove_base.so
[ 98%] Built target move_base
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j4 -l4" failed

2018-07-22 23:08 UTC, moriarty commented
It's strange that I can't reproduce this compile error.
I recently cleaned up my work-space when I found #80 

Now that the ros-planning/navigation#755 is merged, we can merge in #81.

First, I'll delete my work-space and try to reproduce.

Can you provide some info on how you installed OpenCV? And which version it is?

Also, before accepting this could you clean up the commit message a bit?
the first bit is fine it doesn't need _so much_ compile error output.
https://chris.beams.io/posts/git-commit/

2018-07-22 23:39 UTC, josiahls commented
I'll clean it up tonight and try it out on a different computer. I will
also verify the opencv version.

Thanks,
Josiah L.

On Sun, Jul 22, 2018, 7:08 PM Alex Moriarty <notifications@github.com>
wrote:

> It's strange that I can't reproduce this compile error.
> I recently cleaned up my work-space when I found #80
> <https://github.com/fetchrobotics/fetch_ros/pull/80>
>
> Now that the ros-planning/navigation#755
> <https://github.com/ros-planning/navigation/pull/755> is merged, we can
> merge in #81 <https://github.com/fetchrobotics/fetch_ros/pull/81>.
>
> First, I'll delete my work-space and try to reproduce.
>
> Can you provide some info on how you installed OpenCV? And which version
> it is?
>
> Also, before accepting this could you clean up the commit message a bit?
> the first bit is fine it doesn't need *so much* compile error output.
> https://chris.beams.io/posts/git-commit/
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/fetchrobotics/fetch_ros/pull/82#issuecomment-406904390>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ATAdc7sSY9UUOpOD6ReVSCyAH1VGPR31ks5uJQX3gaJpZM4VaKYX>
> .
>

2018-07-22 23:45 UTC, moriarty commented
Thanks.

I cleaned up my workspace 3 times (nuclear option: rm -rf the build, devel, logs and install directories) and tried with each: **catkin build**, **catkin_make** and **catkin_make_isolated** and wasn't able to reproduce.

2018-07-23 02:30 UTC, moriarty commented
The plane_estimator_ needs the .reset and calls to each setter, because there is no appropriate constructor.

The normals_estimator_ constructor should work fine...

If you can let us know more details then I think the cleaned up commit in a8fe874 can be merged.

2018-07-23 20:16 UTC, josiahls commented
I am using opencv 4.0.0. I updated the above commit message to be a little cleaner, and concise.

I modified the commit to address the primary cause of the error. I believe the `normals_estimator_ and plane_estimator_ both` need to use the `reset()` method since they are both smart pointers.

Opencv was installed via  [git and cmake](https://docs.opencv.org/3.4.1/d2/de6/tutorial_py_setup_in_ubuntu.html)

The way that opencv 4.0.0 docs, and current boost smart pointer docs specify smart pointer usage is to use the `reset()` method. I do not understand why the compiler error does not happen on your system, however my system is completely wiped, using the newest opencv , ubuntu 18.04.
```
normals_estimator_.reset(new RgbdNormals(cv_ptr->image.rows,
                                               cv_ptr->image.cols,  
                                               cv_ptr->image.depth(),
                                               K_));
```

2018-07-23 20:41 UTC, josiahls commented
Ok I think I know why this compiler error happens. You need to have the newest version of Opencv:

Compare [opencv 4.0.0](https://docs.opencv.org/master/d1/d5b/classcv_1_1rgbd_1_1RgbdNormals.html)
Compare [opencv 3.0.0](https://docs.opencv.org/3.0.0/d1/d5b/classcv_1_1rgbd_1_1RgbdNormals.html)

Version 4.0.0 uses: `create()` for returning a `Ptr<RgbdNormals>`
Version 3.0.0 not sure. The `create` method is not implemented here. The class uses `Additional Inherited Members` which return `Ptr` but otherwise I am not sure how the `new RgbdNormals` converts to a `Ptr`.

What this tells me is that as of 4.0.0, you need to call `create()` if you want to get a `Ptr`. I still stand by just using `reset()` however. Let me know if that makes sense.

So...

If you update to opencv 4.0.0, you will get the compiler error. That is why wiping the workspace didn't make a difference.

2018-07-23 20:50 UTC, josiahls commented
I am using opencv 4.0.0. I updated the above commit message to be a little cleaner, and concise.

I modified the commit to address the primary cause of the error. I believe the normals_estimator_ and plane_estimator_ both need to use the `reset()` method since they are both smart pointers.

2018-07-27 00:33 UTC, moriarty commented
Okay OpenCV 4.0.0 is still in pre-release. So that's why you have the error and we haven't seen it.

2019-02-14 19:05 UTC, moriarty requested changes
sorry for the long delay. just a little whitespace fix and then I think we can merge this with a squash and merge to keep the commits tidy.

2019-02-14 19:05 UTC, moriarty commented on fetch_depth_layer/src/depth_layer.cpp
> +                                               cv_ptr->image.cols,
```suggestion
                                               cv_ptr->image.cols,
```

2019-02-14 19:05 UTC, moriarty commented on fetch_depth_layer/src/depth_layer.cpp
> +                                               cv_ptr->image.cols,
remove extra whitespace and then this can be merged via the GitHub `squash & merge` feature to cleanup the commit message from the first commit

2019-03-14 21:47 UTC, closed without merging